//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_UX_WIN_Unit_Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NS_UX_WIN_Unit_Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;news&quot;: {&quot;headline&quot;: &quot;The former US ambassador to Ukraine was recalled abruptly in May despite a distinguished career as the president pushed for Kyiv to investigate his rivals&quot;, &quot;source&quot;: &quot;Theguardian.com&quot;}, &quot;track&quot;: {&quot;artists&quot;: [&quot;Senses May Wither&quot;], &quot;duration&quot;: &quot;3:40&quot;, &quot;name&quot;: &quot;Rivals&quot;, &quot;popularity&quot;: 0, &quot;preview_url&quot;: &quot;https://p.scdn.co/mp3-preview/8db5f0d8666c989970b030f7c815b6617244ba5c?cid=59d69939675a46f69725901dd4e309cb&quot;, &quot;external_url&quot;: &quot;https://open.spotify.com/track/3DF505YdORtnimYwAX0Wmy&quot;}}, { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mock_json_input_with_news {
            get {
                return ResourceManager.GetString("mock_json_input_with_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;news&quot;: {}, &quot;track&quot;: {&quot;artists&quot;: [&quot;Post Malone&quot;], &quot;duration&quot;: &quot;3:35&quot;, &quot;name&quot;: &quot;Circles&quot;, &quot;popularity&quot;: 100, &quot;preview_url&quot;: &quot;&quot;, &quot;external_url&quot;: &quot;https://open.spotify.com/track/21jGcNKet2qwijlDFuPiPb&quot;}}, {&quot;news&quot;: {}, &quot;track&quot;: {&quot;artists&quot;: [&quot;Post Malone&quot;, &quot;Ozzy Osbourne&quot;, &quot;Travis Scott&quot;], &quot;duration&quot;: &quot;3:50&quot;, &quot;name&quot;: &quot;Take What You Want (feat. Ozzy Osbourne &amp; Travis Scott)&quot;, &quot;popularity&quot;: 92, &quot;preview_url&quot;: &quot;&quot;, &quot;external_url&quot;: &quot;https://open.spotify.com/track/7CZyCXKG6d5ALeq41sLzbw&quot;}}, {&quot;news&quot;: {}, &quot;track&quot;: {&quot;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mock_json_input_without_news {
            get {
                return ResourceManager.GetString("mock_json_input_without_news", resourceCulture);
            }
        }
    }
}
